### ISSUE TITLE
Allow AWS keys to be optional

### ISSUE THREAD

**Issue by NickLarsenNZ** [Roosterfish/aws-route53-record-set-action#1]
I'm using a github action to assume a role, so my credentials/session key are already set.
It would be nice to not have to supply them again.

Eg:
```yml
    - name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::XXXXXXXXXXXXX:role/example-role
        role-duration-seconds: 1200

    - name: Upsert DNS Record
      uses: Roosterfish/aws-route53-record-set-action@master
      with:
        # No need to set the access key
        # aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_route53_hosted_zone_id: Z9876312478623
        aws_route53_rr_action: "CREATE"
        aws_route53_rr_name: "your-fqdn.example.com"
        aws_route53_rr_type: "A"
        aws_route53_rr_ttl: "300"
        aws_route53_rr_value: "1.2.3.4"

```
